/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Control.DenunciaControlador;
import Modelo.Denuncia;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author jorge
 */
public class Proxy_denuncia extends javax.swing.JFrame {

    /**
     * Creates new form Proxy_sistema
     */
    public Proxy_denuncia() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("SISTEMA DE DENUNCIA - DENUNCIA");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        BTN_REGISTRAR = new javax.swing.JButton();
        BTN_ACTUALIZAR = new javax.swing.JButton();
        BTN_ELIMINAR = new javax.swing.JButton();
        BTN_CONSULTAR = new javax.swing.JButton();
        BTN_USUARIO = new javax.swing.JButton();
        BTN_DENUNCIA = new javax.swing.JButton();
        BTN_AGRESOR = new javax.swing.JButton();
        BTN_CERRAR = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TXT_IDU = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TXT_IDD = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TXT_IDA = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TXT_DESCRIPCION = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TXT_ESTADO = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        TXT_TIPO = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        TXT_RELACION = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        TXT_FECHA = new javax.swing.JTextField();
        BTN_LIMPIAR = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        jMenuItem4.setText("jMenuItem4");

        jMenuItem5.setText("jMenuItem5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        BTN_REGISTRAR.setText("Registrar Denuncia");
        BTN_REGISTRAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_REGISTRARActionPerformed(evt);
            }
        });

        BTN_ACTUALIZAR.setText("Actualizar Denuncia");
        BTN_ACTUALIZAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_ACTUALIZARActionPerformed(evt);
            }
        });

        BTN_ELIMINAR.setText("Eliminar Denuncia");
        BTN_ELIMINAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_ELIMINARActionPerformed(evt);
            }
        });

        BTN_CONSULTAR.setText("Consultar Denuncia");
        BTN_CONSULTAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_CONSULTARActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(BTN_REGISTRAR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BTN_ACTUALIZAR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BTN_ELIMINAR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(BTN_CONSULTAR))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(BTN_REGISTRAR)
                .addGap(18, 18, 18)
                .addComponent(BTN_ACTUALIZAR)
                .addGap(18, 18, 18)
                .addComponent(BTN_ELIMINAR)
                .addGap(18, 18, 18)
                .addComponent(BTN_CONSULTAR)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        BTN_USUARIO.setText("USUARIO");
        BTN_USUARIO.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BTN_USUARIO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_USUARIOActionPerformed(evt);
            }
        });

        BTN_DENUNCIA.setText("DENUNCIA");
        BTN_DENUNCIA.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BTN_DENUNCIA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_DENUNCIAActionPerformed(evt);
            }
        });

        BTN_AGRESOR.setText("AGRESOR");
        BTN_AGRESOR.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BTN_AGRESOR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_AGRESORActionPerformed(evt);
            }
        });

        BTN_CERRAR.setText("Cerrar");
        BTN_CERRAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_CERRARActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Relacion Denunciante");

        TXT_IDU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXT_IDUActionPerformed(evt);
            }
        });

        jLabel2.setText("ID Denuncia");

        TXT_IDD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXT_IDDActionPerformed(evt);
            }
        });

        jLabel3.setText("Descripcion");

        TXT_IDA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXT_IDAActionPerformed(evt);
            }
        });

        jLabel4.setText("Estado");

        jLabel5.setText("ID usuario");

        jLabel6.setText("ID Agresor");

        jLabel7.setText("Tipo de violencia");

        jLabel8.setText("Fecha");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(TXT_IDA)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(TXT_IDU, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(73, 73, 73)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(TXT_DESCRIPCION))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TXT_IDD, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(118, 118, 118))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(TXT_ESTADO, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                            .addComponent(TXT_TIPO, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TXT_RELACION, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TXT_FECHA, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TXT_IDU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TXT_IDD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TXT_IDA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TXT_DESCRIPCION, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TXT_ESTADO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TXT_TIPO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TXT_RELACION, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(TXT_FECHA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(123, Short.MAX_VALUE))
        );

        BTN_LIMPIAR.setText("Limpiar");
        BTN_LIMPIAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_LIMPIARActionPerformed(evt);
            }
        });
        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BTN_USUARIO, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(BTN_DENUNCIA, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(BTN_AGRESOR, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BTN_LIMPIAR)
                            .addComponent(BTN_CERRAR))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BTN_USUARIO)
                    .addComponent(BTN_DENUNCIA)
                    .addComponent(BTN_AGRESOR))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, Short.MAX_VALUE)
                        .addComponent(BTN_LIMPIAR)
                        .addGap(18, 18, 18)
                        .addComponent(BTN_CERRAR)
                        .addGap(57, 57, 57))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTN_REGISTRARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_REGISTRARActionPerformed
      Denuncia denuncia = new Denuncia();
    denuncia.setIdDenuncia(TXT_IDD.getText());
    denuncia.setFec(TXT_FECHA.getText());
    denuncia.setDesc(TXT_DESCRIPCION.getText());
    denuncia.setEstado(TXT_ESTADO.getText());
    denuncia.setTipo(TXT_TIPO.getText());
    denuncia.setRelDenc(TXT_RELACION.getText());
    denuncia.setId_usuario(TXT_IDU.getText());
    denuncia.setId_agresor(TXT_IDA.getText());

    // Llamar al método crearDenuncia del controlador
    DenunciaControlador controlador = new DenunciaControlador();
    try {
        controlador.crearDenuncia(denuncia);
        JOptionPane.showMessageDialog(this, "Denuncia registrada exitosamente.");
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error al registrar la denuncia: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_BTN_REGISTRARActionPerformed

    private void BTN_ACTUALIZARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_ACTUALIZARActionPerformed
        Denuncia denuncia = new Denuncia();
    denuncia.setIdDenuncia(TXT_IDD.getText());
    denuncia.setFec(TXT_FECHA.getText());
    denuncia.setDesc(TXT_DESCRIPCION.getText());
    denuncia.setEstado(TXT_ESTADO.getText());
    denuncia.setTipo(TXT_TIPO.getText());
    denuncia.setRelDenc(TXT_RELACION.getText());
    denuncia.setId_usuario(TXT_IDU.getText());
    denuncia.setId_agresor(TXT_IDA.getText());

        DenunciaControlador controlador = new DenunciaControlador();
    try {
        controlador.actualizarDenuncia(denuncia);
        JOptionPane.showMessageDialog(this, "Denuncia actualizada exitosamente.");
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error al actualizar la denuncia: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_BTN_ACTUALIZARActionPerformed

    private void BTN_USUARIOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_USUARIOActionPerformed
        Proxy_usuario ventana_usuario = new Proxy_usuario();
        ventana_usuario.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BTN_USUARIOActionPerformed

    private void BTN_DENUNCIAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_DENUNCIAActionPerformed
        Proxy_denuncia ventana_denuncia = new Proxy_denuncia();
        ventana_denuncia.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BTN_DENUNCIAActionPerformed

    private void BTN_AGRESORActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_AGRESORActionPerformed
        Proxy_agresor ventana_agresor = new Proxy_agresor();
        ventana_agresor.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BTN_AGRESORActionPerformed

    private void BTN_CERRARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_CERRARActionPerformed
        this.dispose();
    }//GEN-LAST:event_BTN_CERRARActionPerformed

    private void TXT_IDUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXT_IDUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXT_IDUActionPerformed

    private void TXT_IDDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXT_IDDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXT_IDDActionPerformed

    private void TXT_IDAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXT_IDAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXT_IDAActionPerformed

    private void BTN_LIMPIARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_LIMPIARActionPerformed
        TXT_IDU.setText("");      // Limpia el campo de nombre
        TXT_IDD.setText("");    // Limpia el campo de apellido
        TXT_IDA.setText("");       // Limpia el campo de email
        TXT_DESCRIPCION.setText("");    // Limpia el campo de teléfono
        TXT_ESTADO.setText("");   // Limpia el campo de dirección
        TXT_RELACION.setText("");
        TXT_TIPO.setText("");
          TXT_FECHA.setText("");
    }//GEN-LAST:event_BTN_LIMPIARActionPerformed

    private void BTN_CONSULTARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_CONSULTARActionPerformed
    String idDenuncia = TXT_IDD.getText();

    // Llamar al método leerDenuncia del controlador
    DenunciaControlador controlador = new DenunciaControlador();
    try {
        Denuncia denuncia = controlador.leerDenuncia(idDenuncia);
        if (denuncia != null) {
            // Rellenar los campos del formulario con los datos de la denuncia
            TXT_FECHA.setText(denuncia.getFec());
            TXT_DESCRIPCION.setText(denuncia.getDesc());
            TXT_ESTADO.setText(denuncia.getEstado());
            TXT_TIPO.setText(denuncia.getTipo());
            TXT_RELACION.setText(denuncia.getRelDenc());
            TXT_IDU.setText(denuncia.getId_usuario());
            TXT_IDA.setText(denuncia.getId_agresor());
            JOptionPane.showMessageDialog(this, "Denuncia encontrada y datos cargados.");
        } else {
            JOptionPane.showMessageDialog(this, "No se encontró ninguna denuncia con el ID proporcionado.", "Información", JOptionPane.INFORMATION_MESSAGE);
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error al consultar la denuncia: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_BTN_CONSULTARActionPerformed

    private void BTN_ELIMINARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_ELIMINARActionPerformed
       String idDenuncia = TXT_IDD.getText();

    DenunciaControlador controlador = new DenunciaControlador();
    try {
        controlador.eliminarDenuncia(idDenuncia);
        JOptionPane.showMessageDialog(this, "Denuncia eliminada exitosamente.");
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error al eliminar la denuncia: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_BTN_ELIMINARActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Proxy_denuncia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Proxy_denuncia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Proxy_denuncia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Proxy_denuncia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Proxy_denuncia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_ACTUALIZAR;
    private javax.swing.JButton BTN_AGRESOR;
    private javax.swing.JButton BTN_CERRAR;
    private javax.swing.JButton BTN_CONSULTAR;
    private javax.swing.JButton BTN_DENUNCIA;
    private javax.swing.JButton BTN_ELIMINAR;
    private javax.swing.JButton BTN_LIMPIAR;
    private javax.swing.JButton BTN_REGISTRAR;
    private javax.swing.JButton BTN_USUARIO;
    private javax.swing.JTextField TXT_DESCRIPCION;
    private javax.swing.JTextField TXT_ESTADO;
    private javax.swing.JTextField TXT_FECHA;
    private javax.swing.JTextField TXT_IDA;
    private javax.swing.JTextField TXT_IDD;
    private javax.swing.JTextField TXT_IDU;
    private javax.swing.JTextField TXT_RELACION;
    private javax.swing.JTextField TXT_TIPO;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
