/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;
import Control.*;
import Modelo.Usuario;
import java.sql.SQLException;
import javax.swing.JOptionPane;
/**
 *
 * @author jorge
 */
public class Proxy_usuario extends javax.swing.JFrame {

    /**
     * Creates new form Proxy_sistema
     */
    public Proxy_usuario() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("SISTEMA DE DENUNCIA - USUARIO");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JSeparator();
        BTN_DENUNCIA = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        BTN_REGISTRAR = new javax.swing.JButton();
        BTN_ACTUALIZAR = new javax.swing.JButton();
        BTN_ELIMINAR = new javax.swing.JButton();
        BTN_CONSULTAR = new javax.swing.JButton();
        BTN_USUARIO = new javax.swing.JButton();
        BTN_DENUNCIA1 = new javax.swing.JButton();
        BTN_AGRESOR = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TXT_NOMBRE = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TXT_APELLIDO = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TXT_EMAIL = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TXT_TELEFONO = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TXT_DIRECCION = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        TXT_ID = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        TXT_TIPO = new javax.swing.JTextField();
        BTN_CERRAR = new javax.swing.JButton();
        BTN_LIMPIAR = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        jMenuItem4.setText("jMenuItem4");

        jMenuItem5.setText("jMenuItem5");

        BTN_DENUNCIA.setText("DENUNCIA");
        BTN_DENUNCIA.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BTN_DENUNCIA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_DENUNCIAActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        BTN_REGISTRAR.setText("Registrar usuario");
        BTN_REGISTRAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_REGISTRARActionPerformed(evt);
            }
        });

        BTN_ACTUALIZAR.setText("Actualizar usuario");
        BTN_ACTUALIZAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_ACTUALIZARActionPerformed(evt);
            }
        });

        BTN_ELIMINAR.setText("Eliminar usuario");
        BTN_ELIMINAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_ELIMINARActionPerformed(evt);
            }
        });

        BTN_CONSULTAR.setText("Consultar usuario");
        BTN_CONSULTAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_CONSULTARActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(BTN_REGISTRAR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BTN_ACTUALIZAR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BTN_ELIMINAR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(BTN_CONSULTAR))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(BTN_REGISTRAR)
                .addGap(18, 18, 18)
                .addComponent(BTN_ACTUALIZAR)
                .addGap(18, 18, 18)
                .addComponent(BTN_ELIMINAR)
                .addGap(18, 18, 18)
                .addComponent(BTN_CONSULTAR)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        BTN_USUARIO.setText("USUARIO");
        BTN_USUARIO.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BTN_USUARIO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_USUARIOActionPerformed(evt);
            }
        });

        BTN_DENUNCIA1.setText("DENUNCIA");
        BTN_DENUNCIA1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BTN_DENUNCIA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_DENUNCIA1ActionPerformed(evt);
            }
        });

        BTN_AGRESOR.setText("AGRESOR");
        BTN_AGRESOR.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BTN_AGRESOR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_AGRESORActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Nombre");

        TXT_NOMBRE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXT_NOMBREActionPerformed(evt);
            }
        });

        jLabel2.setText("Apellido");

        TXT_APELLIDO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXT_APELLIDOActionPerformed(evt);
            }
        });

        jLabel3.setText("Email");

        TXT_EMAIL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXT_EMAILActionPerformed(evt);
            }
        });

        jLabel4.setText("Telefono");

        jLabel5.setText("Dirección");

        jLabel6.setText("ID");

        jLabel7.setText("Tipo");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(TXT_TELEFONO, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                            .addComponent(TXT_EMAIL, javax.swing.GroupLayout.Alignment.LEADING))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(TXT_DIRECCION)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(TXT_NOMBRE, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TXT_APELLIDO, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(118, 118, 118))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TXT_TIPO, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TXT_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TXT_NOMBRE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(TXT_APELLIDO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TXT_EMAIL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TXT_TELEFONO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(TXT_DIRECCION, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(TXT_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(TXT_TIPO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(157, Short.MAX_VALUE))
        );

        BTN_CERRAR.setText("Cerrar");
        BTN_CERRAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_CERRARActionPerformed(evt);
            }
        });

        BTN_LIMPIAR.setText("Limpiar");
        BTN_LIMPIAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_LIMPIARActionPerformed(evt);
            }
        });
        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BTN_USUARIO, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BTN_DENUNCIA1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BTN_AGRESOR, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BTN_LIMPIAR)
                            .addComponent(BTN_CERRAR)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTN_USUARIO)
                    .addComponent(BTN_DENUNCIA1)
                    .addComponent(BTN_AGRESOR))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(27, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BTN_LIMPIAR)
                        .addGap(45, 45, 45)
                        .addComponent(BTN_CERRAR)
                        .addGap(61, 61, 61))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTN_REGISTRARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_REGISTRARActionPerformed
         UsuarioControlador registrar = new UsuarioControlador();
        String idUsuario = TXT_ID.getText();
        String nombre = TXT_NOMBRE.getText();
        String apellido = TXT_APELLIDO.getText();
        String email = TXT_EMAIL.getText();
        String telefono = TXT_TELEFONO.getText();
        String direccion = TXT_DIRECCION.getText();
        String tipoUsuario = TXT_TIPO.getText();
        Usuario USER = new Usuario(idUsuario, nombre, apellido, email, telefono, direccion, tipoUsuario);
        try {
        registrar.crearUsuario(USER);
        JOptionPane.showMessageDialog(this, "Usuario registrado con éxito");
    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error al registrar el usuario");
    }
        
    }//GEN-LAST:event_BTN_REGISTRARActionPerformed

    private void BTN_ACTUALIZARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_ACTUALIZARActionPerformed
       UsuarioControlador controlador = new UsuarioControlador();
    
    // Obtener los valores de los campos de texto
     String idUsuario = TXT_ID.getText();
        String nombre = TXT_NOMBRE.getText();
        String apellido = TXT_APELLIDO.getText();
        String email = TXT_EMAIL.getText();
        String telefono = TXT_TELEFONO.getText();
        String direccion = TXT_DIRECCION.getText();
        String tipoUsuario = TXT_TIPO.getText();
    
    // Crear el objeto Usuario con los valores obtenidos de los JTextFields
    Usuario usuario = new Usuario(idUsuario, nombre, apellido, email, telefono, direccion, tipoUsuario);
    
    // Llamar al método actualizarUsuario del controlador
    try {
        controlador.actualizarUsuario(usuario);
        JOptionPane.showMessageDialog(this, "Usuario actualizado con éxito");
    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error al actualizar el usuario");
    }
    }//GEN-LAST:event_BTN_ACTUALIZARActionPerformed

    private void BTN_USUARIOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_USUARIOActionPerformed
        Proxy_usuario ventana_usuario = new Proxy_usuario();
        ventana_usuario.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BTN_USUARIOActionPerformed

    private void BTN_DENUNCIAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_DENUNCIAActionPerformed
        Proxy_denuncia ventana_denuncia = new Proxy_denuncia();
        ventana_denuncia.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BTN_DENUNCIAActionPerformed

    private void BTN_DENUNCIA1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_DENUNCIA1ActionPerformed
        Proxy_denuncia ventana_denuncia = new Proxy_denuncia();
        ventana_denuncia.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BTN_DENUNCIA1ActionPerformed

    private void BTN_AGRESORActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_AGRESORActionPerformed
        Proxy_agresor ventana_agresor = new Proxy_agresor();
        ventana_agresor.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BTN_AGRESORActionPerformed

    private void TXT_NOMBREActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXT_NOMBREActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXT_NOMBREActionPerformed

    private void TXT_EMAILActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXT_EMAILActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXT_EMAILActionPerformed

    private void TXT_APELLIDOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXT_APELLIDOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXT_APELLIDOActionPerformed

    private void BTN_ELIMINARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_ELIMINARActionPerformed
        UsuarioControlador controlador = new UsuarioControlador();
    
    // Obtener el idUsuario del JTextField
    String idUsuario = TXT_ID.getText();
    
    // Llamar al método eliminarUsuario del controlador
    try {
        controlador.eliminarUsuario(idUsuario);
        JOptionPane.showMessageDialog(this, "Usuario eliminado con éxito");
    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error al eliminar el usuario");
    }
        
        
    }//GEN-LAST:event_BTN_ELIMINARActionPerformed

    private void BTN_CONSULTARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_CONSULTARActionPerformed
         UsuarioControlador controlador = new UsuarioControlador();
    
    // Obtener el idUsuario del JTextField
    String idUsuario = TXT_ID.getText();
    
    try {
        // Llamar al método leerUsuario y obtener el objeto Usuario
        Usuario usuario = controlador.leerUsuario(idUsuario);
        
        // Verificar si el usuario fue encontrado
        if (usuario != null) {
            // Mostrar los datos del usuario en los JTextFields
            TXT_NOMBRE.setText(usuario.getNombre());
            TXT_APELLIDO.setText(usuario.getApellido());
            TXT_EMAIL.setText(usuario.getEmail());
            TXT_TELEFONO.setText(usuario.getTelefono());
            TXT_DIRECCION.setText(usuario.getDireccion());
            TXT_TIPO.setText(usuario.getTipoUsuario());
            JOptionPane.showMessageDialog(this, "Usuario encontrado y datos cargados");
        } else {
            JOptionPane.showMessageDialog(this, "Usuario no encontrado");
        }
    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error al leer el usuario");
    }
    }//GEN-LAST:event_BTN_CONSULTARActionPerformed

    private void BTN_CERRARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_CERRARActionPerformed
        this.dispose();
    }//GEN-LAST:event_BTN_CERRARActionPerformed

    private void BTN_LIMPIARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_LIMPIARActionPerformed
          TXT_NOMBRE.setText("");      // Limpia el campo de nombre
    TXT_APELLIDO.setText("");    // Limpia el campo de apellido
    TXT_EMAIL.setText("");       // Limpia el campo de email
    TXT_TELEFONO.setText("");    // Limpia el campo de teléfono
    TXT_DIRECCION.setText("");   // Limpia el campo de dirección
    TXT_TIPO.setText(""); 
    }//GEN-LAST:event_BTN_LIMPIARActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Proxy_usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Proxy_usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Proxy_usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Proxy_usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Proxy_usuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_ACTUALIZAR;
    private javax.swing.JButton BTN_AGRESOR;
    private javax.swing.JButton BTN_CERRAR;
    private javax.swing.JButton BTN_CONSULTAR;
    private javax.swing.JButton BTN_DENUNCIA;
    private javax.swing.JButton BTN_DENUNCIA1;
    private javax.swing.JButton BTN_ELIMINAR;
    private javax.swing.JButton BTN_LIMPIAR;
    private javax.swing.JButton BTN_REGISTRAR;
    private javax.swing.JButton BTN_USUARIO;
    private javax.swing.JTextField TXT_APELLIDO;
    private javax.swing.JTextField TXT_DIRECCION;
    private javax.swing.JTextField TXT_EMAIL;
    private javax.swing.JTextField TXT_ID;
    private javax.swing.JTextField TXT_NOMBRE;
    private javax.swing.JTextField TXT_TELEFONO;
    private javax.swing.JTextField TXT_TIPO;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
